version: '3.8'

services:
  mindswap-mysql:
    image: mysql:8.0
    container_name: mindswap-mysql
    ports:
      - '3306:3306'

    environment:
      MYSQL_ROOT_PASSWORD: 'mypass'
      MYSQL_DATABASE: 'urlcompress'
    restart: always


#  mindswap-app:
#    image: url_service
#    restart: on-failure
#    container_name: mindswap-app
#    depends_on:
#      - mindswap-mysql
#    ports:
#      - '8080:8080'
#
#    environment:
#      MYSQL_DATABASE: 'urlcompress'
#      MYSQL_USER: 'root'
#      MYSQL_ROOT_PASSWORD: 'mypass'
#      MYSQL_URL: jdbc:mysql://localhost:3306/url_compress
#      SERVER_PORT: '8080'
#      HIBERNATE_DDL_AUTO: 'create-drop'#